### PR TITLE
Improvements for top-positioned message

### PR DESCRIPTION
**Pull request by shkoliar**
- Fixed bug when message goes out of screen when iOS keyboard appears.
- Fixed bug when message is not visible after showMessage call with visible iOS keyboard (message placed out of visible screen frame).

### CODE REVIEW

**Comment by wxxsw** [comment]
@DmitryNek Cool!

**Comment by wxxsw** [comment]
@DmitryNek I'm sorry, I have to undo this merger because this submission will cause the message to not display correctly when the navigation bar is opaque. You can run the Example project in your fork project to see. Thank you!

**Comment by shkoliar** [comment]
@wxxsw yes, you were right. I've added fix for that with last commit in my forked repo.

**Comment by wxxsw** [comment]
@DmitryNek Great, I've merged.

**Pull request merged**
