### PR TITLE
modify calculatePosition and add option border

### PR DESCRIPTION
**Pull request by epilo9er**
1. Modify calculatePosition function for isInsideSafeAreaInsets and inViewController.
2. Add option, border for messageView

Please check this! :)
And happy for your day.

### CODE REVIEW

**Comment by wxxsw** [comment]
Thank you. But it seems that this commit will break the behavior of the navigation bar when it is hidden or transparent (the message view extends to the top or bottom)

**Comment by epilo9er** [comment]
You mean, the navigation bar was hidden programmatically. Right?
Like this, "navigationController?.isNavigationBarHidden = true".

Or, can i test that case?

My apps use the navigation controller, and It works normally.

**Comment by epilo9er** [comment]
Oh! I see. 
I re-build demo-app and try test that. :)

**Comment by wxxsw** [comment]
You can compare your Fork version of Demo with the Demo in master.

In the Demo, click the "Toggle NavBar Translucent" or "Toggle NavBar Hidden" button, then click on Show Message and you will see the difference.

**Comment by epilo9er** [comment]
Thanks, and i will modify! :)
so this close.

**Pull request closed without merging**
